metadata:
  path: classpath:default/data/metadata.json

protocol:
    path: protocols-directory-is-not-defined


######################
# Spring Boot        #
######################
server:
    port: 8080